### PR TITLE
steamcompmgr: Avoid deadlock between import_commit and destroy_buffer

### PR DESCRIPTION
**Pull request by Joshua-Ashton**
**Take 2!**

Very rarely we can see a deadlock between import_commit and destroy_buffer where:

- destroy_buffer is waiting on `wlr_buffer_map_lock` and has `wlserver_lock` (from up the chain)

- import_commit has `wlr_buffer_map_lock` and is waiting on `wlserver_lock`

To avoid this, we simply replace the lock_guard in import_commit with a unique_lock and manually unlock this before going into the section where we need to lock the wl_server.

This is safe for a few reasons:
- 1: All accesses to wlr_buffer_map are done before this lock.
- 2: destroy_buffer cannot be called from this buffer before now
     as it only happens because of the signal added below.
- 3: "References to elements in the unordered_map container remain
	  valid in all cases, even after a rehash."

### CODE REVIEW

**Comment by Joshua-Ashton** [comment]
cc: @BNieuwenhuizen

**Comment by BNieuwenhuizen** [comment]
LGTM

**Comment by Plagman** [comment]
isn't having the map by wlr_buffer* unsafe to begin with? can't that address get reused?

**Comment by Joshua-Ashton** [comment]
It can be re-used but we remove it in buffer_destroy (which happens before free) so we won't have the re-use problem.

**Comment by emersion** [comment]
Sorry, I don't understand this code, so I can't whether this is correct.

**Comment by Plagman** [comment]
Merged, but it appears we now have an FD leak: https://github.com/Plagman/gamescope/issues/324

**Pull request closed without merging**
