### PR TITLE
Work for Forza Horizon 5 registering

### PR DESCRIPTION
**Pull request by Joshua-Ashton**

### CODE REVIEW

**Comment by Plagman** [comment]
Merged the transient link fix from the other PR - the repaint on focus change is going to need a bit more work, see discussion on Gitlab. 

Any reason why we actually have to keep the o-r windows in their original positions and can't move them like all others, just remembering their offset ourselves? I'm worried part of them might end up offscreen then and cause mouse pointer issues.

**Comment by Joshua-Ashton** [comment]
> Any reason why we actually have to keep the o-r windows in their original positions and can't move them like all others, just remembering their offset ourselves? I'm worried part of them might end up offscreen then and cause mouse pointer issues.

Right now we only do that for the focus window, I haven't seen any real reason to move them to 0,0.

What sort of mouse cursor issues are you expecting? We move the barricades relative to the x/y position of the override now and warp within those if we ever escape it.

**Comment by Joshua-Ashton** [comment]
Opened for review.

**Comment by Plagman** [comment]
The common cursor problem is that the cursor can't go past the screen extents. So if the popup is close to the bottom/right edge and we don't place it at all, part of it might be inaccessible by the cursor. Given it's o-r, I guess it's up to the client to place it so it won't do that? (WMs can't typically place o-r windows right?)

**Comment by Joshua-Ashton** [comment]
For o-r's that go offfscreen, the cursor is allowed to go there.

**Comment by Plagman** [comment]
By whom? I'm not talking about our code - the X server will not let the pointer just go offscreen unfortunately. I've often wanted it to, and we used to carry patches to that effect in old SteamOS, but not right now.

**Comment by emersion** [comment]
> Given it's o-r, I guess it's up to the client to place it so it won't do that? (WMs can't typically place o-r windows right?)

Yes. Clients are responsible for picking on-screen coordinates for o-r windows.

**Review by Plagman — COMMENTED** [review]
its

**Comment by Joshua-Ashton** [comment]
:frog: fixed

**Pull request merged**
