### PR TITLE
Fixed typing the EURO symbol using the on-screen keyboard

### PR DESCRIPTION
**Pull request by slouken**

### CODE REVIEW

**Comment by emersion** [comment]
Do we have a libxkbcommon fix for this too?

**Comment by slouken** [comment]
> Do we have a libxkbcommon fix for this too?

Yep:
```patch
diff --git a/src/keysym-utf.c b/src/keysym-utf.c
index 7769672..f36f854 100644
--- a/src/keysym-utf.c
+++ b/src/keysym-utf.c
@@ -819,7 +819,7 @@ static const struct codepair keysymtab[] = {
     { 0x0ef9, 0x11f0 }, /*  Hangul_J_KkogjiDalrinIeung ᇰ HANGUL JONGSEONG YESIEUNG */
     { 0x0efa, 0x11f9 }, /*        Hangul_J_YeorinHieuh ᇹ HANGUL JONGSEONG YEORINHIEUH */
     { 0x0eff, 0x20a9 }, /*                  Korean_Won ₩ WON SIGN */
-    { 0x13a4, 0x20ac }, /*                        Euro € EURO SIGN */
+    //{ 0x13a4, 0x20ac }, /*                        Euro € EURO SIGN */
     { 0x13bc, 0x0152 }, /*                          OE Œ LATIN CAPITAL LIGATURE OE */
     { 0x13bd, 0x0153 }, /*                          oe œ LATIN SMALL LIGATURE OE */
     { 0x13be, 0x0178 }, /*                  Ydiaeresis Ÿ LATIN CAPITAL LETTER Y WITH DIAERESIS */
```

**Comment by emersion** [comment]
Can we send this upstream?

**Comment by slouken** [comment]
> Can we send this upstream?

Sure, what's the process?

**Comment by emersion** [comment]
Done in https://github.com/xkbcommon/libxkbcommon/pull/288

**Comment by slouken** [comment]
> Done in [xkbcommon/libxkbcommon#288](https://github.com/xkbcommon/libxkbcommon/pull/288)

Thanks!

**Pull request merged**
