### PR TITLE
Check for current and pending mode_id before abort

### LINKED ISSUE #624: Gamescope fails to run on the 6.0+ kernel
What previously worked with the 5.19 kernel or older no longer works on kernel 6.0. Using `gamescope -- steam` results in an assert error. The same thing happens when trying to use gamescope-session to boot the "Steam Deck" experience like I've been doing for nearly a year now.

Steam running from the desktop works fine.
[gamescope-stdout.log](https://github.com/ValveSoftware/steam-for-linux/files/9583846/gamescope-stdout.log)
[steam-stdout.log](https://github.com/ValveSoftware/steam-for-linux/files/9583847/steam-stdout.log)

I originally opened a ticket for Steam itself, but I was directed here:
https://github.com/ValveSoftware/steam-for-linux/issues/8803#event-7402980486
Steps for reproducing this issue:

    Update to the 6.0 kernel
    Attempt to launch Steam using gamescope from the TTY.
    Observe how this crashes with an assert

### PR DESCRIPTION
**Pull request by Samsagax**
This fixes #624

### CODE REVIEW

**Comment by emersion** [comment]
We still want to fail hard if `g_DRM.pending.mode_id != 0`.

**Comment by Samsagax** [comment]
> We still want to fail hard if `g_DRM.pending.mode_id != 0`.

Should we fail if pending mode is zero, then? I don't see at this point in code if "current" has any meaninful data since the commit soon after that will just squash it. 

The drm_prepare call before that is setting the properties for mode id but it does not update current. Maybe there is some logic I'm not getting right.

**Comment by emersion** [comment]
IOW, this patch is equivalent to replacing the whole if with `if (false)`.

**Comment by Samsagax** [comment]
Mhhh... The error with #624 seems to be further down in the driver. I still wonder why Gamescope is affected but other wlroots compositors like sway are not.

Closing as this change seems to be a moot point.

**Pull request closed without merging**
