### PR TITLE
Add Fedora Requirements

### PR DESCRIPTION
**Pull request by Doomsdayrs**
Add distribution specific requirement chart

### CODE REVIEW

**Comment by emersion** [comment]
This is already documented in https://github.com/Plagman/gamescope/wiki/Distribution-specific-instructions

**Comment by Doomsdayrs** [comment]
That does not help in CLI

**Comment by emersion** [comment]
Sorry, but I'd rather not maintain a list packages for every distribution in the README.

**Comment by Doomsdayrs** [comment]
But that is what you already do? Except you have it under a github specific location, instead of placing it, for example, in a separate readme file so CLI users can easily open it up in the terminal, and the GUI users can easily view it as well.

**Pull request closed without merging**
