### PR TITLE
pipewire: add support for DMA-BUFs

### PR DESCRIPTION
**Pull request by emersion**

### CODE REVIEW

**Comment by slouken** [comment]
Can you rebase your patch on the latest code? I've confirmed that your PR works here.

**Comment by Joshua-Ashton** [comment]
@emersion anything blocking this?

**Comment by emersion** [comment]
> I've confirmed that your PR works here.

How did you test? I'd like to make sure everything looks good from gamescope's side. This PR is missing some cleanup.

**Comment by Joshua-Ashton** [comment]
This would also be ideal as I want to start having other consumers of our PW stuff soon

**Comment by Joshua-Ashton** [comment]
I picked [Add exportable flag to CVulkanTexture](https://github.com/emersion/gamescope/commit/27223f0c0657c6b28b23737e4e9a927d9ff80107) into master because I need it for something else.

**Comment by slouken** [comment]
Any update on this? It would be great to have DMA-BUF capture support on Steam Deck.

**Comment by emersion** [comment]
I've cleaned up the branch. Thanks for testing!

@slouken: FWIW, when running Steam in a nested gamescope window, and resizing while streaming, the Steam client crashes.

**Pull request merged**
