### PR TITLE
wlserver: Fix creating headless backend when nested + correct mode info

### PR DESCRIPTION
**Pull request by Joshua-Ashton**

### CODE REVIEW

**Comment by emersion** [comment]
I am not sure "wlserver: Expose correct mode info for display" is a good idea. We fake the resolution exposed to games, and this commit exposes the real output physical size, which is different and might break games.

**Comment by emersion** [comment]
The first commit LGTM, I wonder why I did not get this when testing? Maybe a rebase broke it.

**Comment by Joshua-Ashton** [comment]
Ill pick the first commit then.

The idea was to expose the native mode to Steam and not affect x clients at all, is wlr/xwayland going to take this and do something silly?

**Comment by emersion** [comment]
The modes are exposed via Xwayland RandR, so bad games can use that to pick their size.

**Pull request closed without merging**
