### PR TITLE
Fix IME generated keycodes to match expected values

### PR DESCRIPTION
**Pull request by slouken**
This fixes the keycode always being '1' for the Steam Deck on-screen
keyboard. Emoji and non-US keys will still use the old code path.

### CODE REVIEW

**Comment by Plagman** [comment]
@emersion to take a peek?

**Comment by slouken** [comment]
FYI, I compared the Steam Deck virtual keyboard and a real keyboard (both with US layout) and their keycodes now match. I also verified that emoji functionality is unaffected.

**Comment by slouken** [comment]
We don't support modifiers at all in this path, so I figured this was the best compromise.

**Comment by emersion** [comment]
The point is:

- Good X11 clients shouldn't interpret raw keycodes, the keycodes don't mean anything without a keymap
- This patch makes it so raw keycodes look a bit more like what would happen with a "real" physical keyboard, but
- This patch doesn't completely make ASCII characters look like what would happen with a "real" physical keyboard, because e.g. uppercase letters and special characters won't be recognized correctly by bad X11 clients

So I wonder what this patch really fixes? Do you have an example game which behaves better with this applied?

**Comment by slouken** [comment]
Here are repro steps:
- Install Darwinia, please use beta branch password "SwooshLandmassCushy", which unlocks a "steamdeck-test" branch (tagged to a version before I added the ISteamUtils::ShowGamepadTextInput)
- Run Darwinia
- Bring up the in-game menu (whatever the button name is on the Deck controller, top right button left of Y)
- Go into Profile > Create New Profile
- You'll have to use the touchscreen for this because the controller focus wasn't working properly for text input controls at the time, but tap the field containing "NewUser"
- Once the text field has focus, hit the Steam button, and bring up the on-screen keyboard
- Try typing alpha-numeric values and note they're all interpreted as "1" by something between the OSK and the game

While this particular game has been fixed upstream, from my experience with SDL, there are many many games and applications which use keycodes instead of text input events, and this seems like a good halfway step to prevent completely breaking them, if we don't want to go the whole way and implement the full keymap approach.

**Comment by tycho** [comment]
> * Install Darwinia, please use beta branch password "SwooshLandmassCushy", which unlocks a "steamdeck-test" branch (tagged to a version before I added the ISteamUtils::ShowGamepadTextInput)
That branch needs to be re-uploaded, I thought we'd finished with it. I'll have something available in an hour or so.

**Comment by tycho** [comment]
> > * Install Darwinia, please use beta branch password "SwooshLandmassCushy", which unlocks a "steamdeck-test" branch (tagged to a version before I added the ISteamUtils::ShowGamepadTextInput)
> 
> That branch needs to be re-uploaded, I thought we'd finished with it. I'll have something available in an hour or so.

OK, done, but only put up a Linux-native build for the moment.

**Comment by emersion** [comment]
Can you try https://github.com/Plagman/gamescope/pull/429?

**Comment by slouken** [comment]
Superceded by https://github.com/Plagman/gamescope/pull/429

**Pull request closed without merging**
