### PR TITLE
Add support for NV12 buffers

### PR DESCRIPTION
**Pull request by emersion**
VA-API test client: https://git.sr.ht/~emersion/vaapi-decoder/tree/gamescope-hack

### CODE REVIEW

**Comment by emersion** [comment]
The colors displayed by Vulkan for NV12 buffers are still incorrect, even though I think the VkFormat is. We likely need to setup [VK_KHR_sampler_ycbcr_conversion](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_sampler_ycbcr_conversion.html).

**Comment by Joshua-Ashton** [comment]
What colours are you seeing? Sampler conversions only do stuff for image views/samplers.

**Comment by emersion** [comment]
I'm seeing a red-ish image: https://l.sr.ht/XwZA.png

We might need some swizzles as well. I've tried one at random (just switch the `bNeedsSwizzle` field) and it makes the image blue-ish.

**Comment by emersion** [comment]
> Sampler conversions only do stuff for image views/samplers so if you aren't compositing it shouldn't do anything? (unless I am missing something)

I'm not well versed into the Vulkan compute things we're doing in gamescope, but I've seen VkSampler usage.

**Comment by Joshua-Ashton** [comment]
Hmmm... that isn't what I'd expect from a bad swizzle here based on the stuff I faced when implementing NV12 in DXVK D3D9 ( https://github.com/doitsujin/dxvk/blob/master/src/d3d9/shaders/d3d9_convert_nv12.comp )

Looking at where this is used yes there is an image view so we definitely need sampler conversion for that.

**Comment by Joshua-Ashton** [comment]
You also have to use a combined image sampler and immutable samplers for ycbcr iirc which would be annoying.

**Comment by Joshua-Ashton** [comment]
Let me know if you need any help with that or want me to do the rework to move to COMBINED and immutable samplers

**Comment by Plagman** [comment]
Bypassing composite is the goal, but we'll need Vulkan composite support for dev and as a potential fallback. We should still merge it even with incomplete Vulkan support, as long as it's not going to be crashy, which it doesn't appear to be.

**Comment by Plagman** [comment]
I guess I didn't strictly answer your question, Josh - feel free to work on the Vulkan stuff, but it shouldn't be blocking this MR and it can be merged as-is, in my opinion (at least as described).

**Comment by Joshua-Ashton** [comment]
:+1:

**Comment by emersion** [comment]
Alright, let's merge this then. Proper Vulkan support can be built on top of existing commits.

**Comment by emersion** [comment]
The tiling artifacts on the NV12 buffers should be fixed by this patch: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/10623

(This doesn't fix the red-ish taint we also have on linear buffers.)

**Pull request merged**
