### PR TITLE
Reorganize and rework the renderer

### PR DESCRIPTION
**Pull request by DadSchoorse**
Remove duplicate image upload paths, unify swapchain/output image handling and reorganize a ton of global state into device + command buffer classes. The command buffer class manages all the descriptor state and automatically adds barriers, which really simplifies the actual compute dispatch code a lot. (The tracking could certainly be better, but we don't have any opportunities for overlapping dispatches anyway.)

On the side this also fixes NIS quality, previously its final blit didn't sample at the pixel center. Also resolves a ton of issues in the upload fallback of vulkan_create_texture_from_wlr_buffer, even if I'm still not sure when that's actually used. But fixing it is trivial now.

### CODE REVIEW

**Comment by Joshua-Ashton** [comment]
While we are here can we cleanup static `getModifierProps` to initialize the structs with designated initalizers. Same with Texture BInit and vulkan_init_format.

I guess stuff looks fine but still not fully clean -- not like we can do worse.

**Comment by DadSchoorse** [comment]
Sure, I can do some style cleanups tomorrow. I guess we could also clang-format `rendervulkan.cpp` in the end to fix some inconsistencies there.

**Comment by Joshua-Ashton** [comment]
We should probably do that across the whole codebase at this point... I am usually not a fan of clang-format, but makes sense when you want to just sweep up a mishmash of styles.

**Comment by pchome** [comment]
> `depfile   : '@BASENAME@.dep',`

I'd use `@BASENAME@.h.d` to match other depfiles in the build.ninja file (e.g. `DEPFILE = gamescope.p/src_ime.cpp.o.d`). And to not confuse with other `_dep` in the meson.build file.

**Pull request merged**
