### PR TITLE
Don't focus SKIP_{TASKBAR,PAGER} windows

### PR DESCRIPTION
**Pull request by emersion**

### CODE REVIEW

**Comment by emersion** [comment]
Marking ready for review because while this doesn't fix Origin, this makes our NET_WM_STATE handling more robust and could avoid some head-scratching if a game relies on these features.

**Comment by emersion** [comment]
Pushed the first three commits on master since they are low-risk.

The remaining commits should fix #87.

**Comment by Plagman** [comment]
This PR scares me a bit

**Comment by emersion** [comment]
> before I try to wrap my head around it too much, was the simplification aimed to have exactly the same outcome in all exotic combinations of those flags?

Yes, that was the intent. The new logic sorts windows like so:

1. Sort windows with `gameID` set first
2. For all windows with `gameID` set, sort the ones which aren't override-redirect first
3. For all windows which aren't override-redirect, sort the ones with `wantsUnfocus` unset first
4. For all windows with `wantsUnfocus` unset, sort the ones with a greater `damage_sequence` first

The fact windows were previously picked from `vecPossibleFocusGameWindows` before `vecPossibleFocusAnyWindows` is now done via (1).  `allowNonGameOverrideRedirectWindow` and `usingOverrideRedirectWindow` are replaced by (2). The final `if ( focus->wantsUnfocus && vecPossibleFocusAnyWindows.size() >= 2 )` check is replaced with (3). The `if ( w->damage_sequence >= maxDamageSequence )` check is replaced by (4).

I now realize that the new logic doesn't re-implement exactly the old one. Previously, non-game windows ignored `damage_sequence`, and game windows ignored `wantsUnfocus`. I can change the PR to do that if desirable, but not sure it really matters: for instance `wantsUnfocus` is set by a special steam property (I can't imagine it being wrongly set on a game window).

This PR implements the "focus score" we've been discussing in the past, except without an explicit score. This makes it easier to tweak the ordering: instead of fine-tuning weights for each criteria, we can just change the priorities in the sort function.

**Comment by emersion** [comment]
Testing status as per https://github.com/Plagman/gamescope/wiki/Quirky-games:

- [ ] Defcon
- [ ] Duke3D Megaton: doesn't exist anymore. Tried Duke Nukem 3D instead, but doesn't start even w/o gamescope. Same for Duke3D Megaton - classic.
- [ ] Long Live the Queen
- [ ] The Bard's Tale
- [ ] Aquaria
- [ ] Wizardry 7
- [ ] Trine 2
- [ ] Hotline Miami
- [ ] Awesomenauts
- [ ] Wargame: European Escalation
- [ ] Planetary Annihilation
- [ ] XCOM

**Pull request merged**
