### PR TITLE
ime: use default keymap if possible

### PR DESCRIPTION
**Pull request by emersion**
Avoids switching the keymap unless necessary.

### CODE REVIEW

**Comment by Plagman** [comment]
Does this supercede Sam's MR?

**Comment by emersion** [comment]
Yeah, this approach should be a superset of Sam's.

**Comment by slouken** [comment]
I tested this, and it looks like the first key pressed isn't mapped for some reason:
```
INFO: Key pressed :  scancode 30 = 1, keycode 0x00000031 = 1  modifiers: (none)
INFO: INPUT Text (\x68): "h"
INFO: Key released:  scancode 30 = 1, keycode 0x00000031 = 1  modifiers: (none)
INFO: Key pressed :  scancode 11 = H, keycode 0x00000068 = H  modifiers: (none)
INFO: INPUT Text (\x68): "h"
INFO: Key released:  scancode 11 = H, keycode 0x00000068 = H  modifiers: (none)
INFO: Key pressed :  scancode 11 = H, keycode 0x00000068 = H  modifiers: (none)
INFO: INPUT Text (\x48): "H"
INFO: Key released:  scancode 11 = H, keycode 0x00000068 = H  modifiers: (none)
```
I also noticed that shifted characters don't end up with SHIFT modifiers, but it looks like they're intended to. Is that right?

Otherwise, this looks good!

**Comment by emersion** [comment]
Ah, right, should be fixed now!

**Comment by slouken** [comment]
It crashes now:
X connection to :1 broken (explicit kill or server shutdown).
Fatal IO error 11 (Resource temporarily unavailable) on X server :0.

**Comment by slouken** [comment]
Saints Row 2 is also affected by this bug. Do we have a fix for the X11 server crash?

**Comment by emersion** [comment]
I was testing with a nested session, and it seems this bug happens only in the embedded session. I pushed a fix!

**Comment by slouken** [comment]
Looks good, thanks!

**Pull request merged**
